version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: motdepassefort
      POSTGRES_DB: portail_rh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
